# Generated by Django 3.2.4 on 2021-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opc_iot_cheff_value', models.FloatField(blank=True, db_column='OPC_IOT_CHEFF_VALUE', null=True)),
                ('opc_iot_energy_value', models.FloatField(blank=True, db_column='OPC_IOT_ENERGY_VALUE', null=True)),
                ('opc_iot_flow_value', models.FloatField(blank=True, db_column='OPC_IOT_FLOW_VALUE', null=True)),
                ('opc_iot_flow_timestamp', models.DateTimeField(blank=True, db_column='OPC_IOT_FLOW_TIMESTAMP', null=True)),
                ('opc_iot_level_value', models.FloatField(blank=True, db_column='OPC_IOT_LEVEL_VALUE', null=True)),
                ('opc_iot_press_value', models.FloatField(blank=True, db_column='OPC_IOT_PRESS_VALUE', null=True)),
                ('opc_iot_temp_value', models.FloatField(blank=True, db_column='OPC_IOT_TEMP_VALUE', null=True)),
            ],
            options={
                'db_table': 'datalog',
                'managed': False,
            },
        ),
    ]
